name: MyApp
options:
  bundleIdPrefix: com.myapp
  deploymentTarget:
    iOS: 13.0
  defaultConfig: Release
  createIntermediateGroups: true
  transitivelyLinkDependencies: true
  tabWidth: 2
  indentWidth: 2

settings:
  base:
    SWIFT_VERSION: 5.1
    CLANG_ENABLE_MODULES: YES
    COPY_PHASE_STRIP: NO

schemes:
  AllTests:
    build:
      targets:
        MyApp: test
        Base: test
        Logging: test
        Testing: test
    test:
      gatherCoverageData: true
      targets:
        - MyAppTests
        - BaseTests
        - LoggingTests
        - TestingTests

include:
  - Projects/templates.yml
  - Projects/MyApp/project.yml
  - Projects/Base/project.yml
  - Projects/Logging/project.yml
  - Projects/Testing/project.yml
